### ISSUE TITLE
[AS] Incomplete "Condtion Code Tests" Support

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#18]
binutils commit: afcc795bc21f5d2972e9bd9d5c52eb91834bf0d0 
binutils branch: arc-2018.09

If you write instructions with _conditional execution_, it only works when the `dest` register and `src1` registers are the same. For instance `add.eq r0, r0, r1` is fine. If they are different (`add.eq r0, r1, r0`), assembler will complain: `test.S:17: Error: inappropriate arguments for opcode 'add'`

Use attached archive as your test bed. Read the `README` file in there.
[as-conditon-codes.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/files/2808304/as-conditon-codes.tar.gz)

**Comment by claziss** [comment]
Hi,
predicated instructions can be only having the destination the second argument. Hence, add.eq r0, r1,r0 doesn't exist :)
