### ISSUE TITLE
[AS] "enter_s [ ]" is not supported for ARCv2

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#19]
Having `enter_s [ ]` which is equivalent to opcode `0xc0e0` is not accepted by the assembler:

```
test.S: Assembler messages:
test.S:267: Error: missing argument
test.S:267: Error: syntax error
```

**Comment by anthony-kolesov** [comment]
Just as a note, `enter_s 0` is accepted and used for example in the GDB testsuite.
https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-2019.03-gdb/gdb/testsuite/gdb.arch/arc-analyze-prologue.S#L236

**Comment by claziss** [comment]
There is no clear request in PRM for enter_s []. The official format is `op u6`. Please use enter_s 0 for special cases.
