### ISSUE TITLE
[AS] "j.d" is not accepted by the assembler

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#20]
If you have an assembly like below:
```
  j.d  @target
  nop_s
  nop_s
target:
  nop_s
  nop_s
```
the assembler will complain:
```
Error: inappropriate arguments for opcode 'j'
```
Same is true for `j_s.d`.

**Comment by shahab-vahedi** [comment]
if you have `j.d` in assembly code you would receive: `Error: inappropriate arguments for opcode 'j'`.

**Comment by claziss** [comment]
All our labels are encoded as 32-bit immediate. The `j.d` instruction allows only `u6` and `s12` shot immediate. Hence your error. The `j_s.d` doesn't allow for any immediate either long or short.
