### ISSUE TITLE
[GDB] Add the "disassembler-option" hook

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#50]
ARC GDB should allow users to override the disassembling options. For instance:

```
(gdb) set disassembler-options cpu=hs38_linux
'set disassembler-options ...' is not supported on this architecture.
```

This will alleviate the problem described [here](https://github.com/foss-for-synopsys-dwc-arc-processors/qemu-private/issues/96#issuecomment-705465748).

### What needs to be done?
Look at this [patch](https://sourceware.org/pipermail/gdb-patches/2021-January/175100.html) for inspiration. Probably we need to define the "set_disassembler_options_arc()" in `opcode/arc-dis.c`.

**Comment by claziss** [comment]
Can we use arc object attributes here? And/or the CPU configuration found in the AUX regs?

**Comment by shahab-vahedi** [comment]
This issue is not about determining the CPU type (see #43 for that). This is mere task to allow the user to determine the CPU manually (as a workaround to #43).

**Comment by shahab-vahedi** [comment]
With all the recurring issues (e.g. #59 ), it is time to work on this promptly.

**Comment by vineetgarc** [comment]
But what is so special about gdb that it needs this hook registetred for an mpu ? while the assembler/disassembler can do this. Its not like we have opcode reuse - LDD is supposed to be a unique opcode. What am I missing here - guess I need a bit of gdb for dummies primer.

**Comment by shahab-vahedi** [comment]
MPU?

**Comment by shahab-vahedi** [comment]
The following patches take care of this issue:

1. [arc: Construct disassembler options dynamically](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=8f467114435286e4f78b16fc1f5864acf6488fc0)
2. [arc: Add 'set disassembler-options' support](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ae61ef2c5615a06f829468b57249a17762a44220)

This is an illustration of usage of the hook by the end user:
```
(gdb) disas $pc,$pc+0x10
Dump of assembler code from 0x100 to 0x110:
=> 0x00000100: mov     r0,0x12345678
   0x00000108: sr      r0,[1120]              # aux reg name not recognized
   0x0000010c: lr      r1,[1120]              # aux reg name not recognized
End of assembler dump.

(gdb) show disassembler-options
The current disassembler options are 'cpu=em4_fpuda'

(gdb) set disassembler-options cpu=archs      # the new added hook

(gdb) disas $pc,$pc+0x10
Dump of assembler code from 0x100 to 0x110:
=> 0x00000100: mov     r0,0x12345678
   0x00000108: sr      r0,[tlbpd0]
   0x0000010c: lr      r1,[tlbpd0]
End of assembler dump.
```
