### ISSUE TITLE
Building gdb 7.9 dev

### ISSUE THREAD

**Issue by leemoore1966** [foss-for-synopsys-dwc-arc-processors/binutils-gdb#9]
Hi Support

I have downloaded the gdb-7.9 branch, and when I build after configuring I get the following error message 

/home/moore/gdbBuild/ARC/gdb-7.9/gas/config/tc-arc.c:93: error: ‘bfd_mach_arc_6’ undeclared here (not in a function)
/home/moore/gdbBuild/ARC/gdb-7.9/gas/config/tc-arc.c:134: error: conflicting types for ‘get_ext_suffix’
/home/moore/gdbBuild/ARC/gdb-7.9/gas/../include/opcode/arc.h:466: note: previous declaration of ‘get_ext_suffix’ was here
/home/moore/gdbBuild/ARC/gdb-7.9/gas/config/tc-arc.c: In function ‘md_parse_option’:
...

Addressing the first issue, the line of source in question is
./gas/config/tc-arc.c:93:static int arc_mach_type = bfd_mach_arc_6; 

the only other references I can find in the entire tree for the text 'bfd_mach_arc_6', is as follows
./gas/ChangeLog-0001:   (arc_mach_type): Make bfd_mach_arc_6 default.
./gas/config/tc-arc.c:static int arc_mach_type = bfd_mach_arc_6;
./gas/config/tc-arc.c:      arc_mach_type = bfd_mach_arc_6;
./bfd/ChangeLog-0001:   (bfd_arc_arch): Make bfd_mach_arc_6 default.
./bfd/ChangeLog-0001:   (arc_elf_final_write_processing): Make bfd_mach_arc_6 default.
./bfd/ChangeLog-0001:   bfd_mach_arc_6, bfd_mach_arc_7, bfd_mach_arc_8 for ARC variants.
./bfd/ChangeLog-0203:   bfd_mach_arc_5, bfd_mach_arc_6, bfd_mach_arc_7, bfd_mach_arc_8,

any ideas ?
Sounds like the compiler is grumbling correctly

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

You need to build only GDB and CGEN simulator from binutils-gdb/arc-7.9-dev:

    make gdb-all sim-all

The reason is that when Binutils and GDB were moving from CVS to Git they started to reside in the same Git repository, since there are several common components and by default Makefile builds all of the targets: binutils and GDB in this case. However in ARC case only GDB has been rebased on top of the latest upstream in this repository, so some of the binutils components are not ported yet (they in fact contain some ages old port for ARC, which is completely out of date. Therefore in `arc-7.9-dev` branch only gdb, sim, opcodes and bfd can be built for ARC, the latter two being prerequisites for GDB.  Gas, ld and binutils cannot be built from that branch.

The problem didn't happen with arc-7.5-dev branch, because back in that time GDB branch in git contained only the actual GDB and its prerequisites, there was no gas, binutils and ld.

**Comment by leemoore1966** [comment]
Hi Anthony

are the configure options the same ?
When I perform 
$ make gdb-all sim-all

I get 
make: *** No rule to make target `gdb-all'. Stop.

Should I still be  attempting to configure/make in the top level directory 'binutils-gdb-arc-7.9', or in the sub-directory 'binutils-gdb-arc-7.9/gdb'

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

Sorry for missing your response. Command for make actually should be `make all-gdb all-sim` - with same configure options. Alternatively you can configure with `--disable-gas --disable-ld --disable-binutils` - then it is possible to call just `make`.

**Comment by leemoore1966** [comment]
Hi Anton,

Many thanks I will try this out.
Lee

**Comment by leemoore1966** [comment]
Hi Anton
Thanks for the info, I have made good progress.
I have now been able to build gdb for Linux(32/64) and Windows/MinGW(32/64)

So from the last release there seem to have been some changes that are causing us some trouble, I wonder if you could suggest how to address this.

We are building gdbservers to act as a target to the client gdb, and we seem to have trouble matching the server to the client when giving the response to a 'g' packet request.
the gdb 'set arch' appears as though it can take the following options

ARC600, A4, A5, ARC600, A6, ARC601, ARC700, A7, ARCv2, EM, HS, auto

How can I determine the list and order of registers which need to be supplied from the server to the client for the above list of possible arch values.

Its always difficult to find the definitive list and order to make a server match the requirements you have placed in the client, could you please provide some guidance on this matter ?

Many Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

Starting from version 7.9 GDB has a support for XML target descriptions, so order of registers is defined by XML file. If no XML file is specified at all, then GDB should fall back to old register order, that has been used in GDB 7.5, so I'm not sure why it would stop working for you with new GDB.

There are some requirements to XML file - first 68 registers has predefined meaning and fixed features. After those XML target description may provide any XML features and registers. List of supported features is described in GDB documentation in section G.4.2 "Target Descriptions / Standard Target Features / ARC Features". You can also look into `gdb/features/arc` directory, which has examples descriptions of required features and registers. It also contains "compatible" register definitions - those are similar to GDB 7.5 fixed register set.

You shouldn't be using `set arch` command in normal case - architecture is read from application ELF file. Also XML target description may contain `<architecture>` tag that will override everything.

**Comment by leemoore1966** [comment]
Hi Anton,

I wonder if I could get some further clarifications here.

> Starting from version 7.9 GDB has a support for XML target 
> descriptions, so order of registers is defined by XML file. If no XML 
> file is specified at all, then GDB should fall back to old register 
> order, that has been used in GDB 7.5, so I'm not sure why it would 
> stop working for you with new GDB.
>

In the previous version of the GDB (7.5.1) we configured the gdb in the 
following manner
(gdb) set architecture EM
(gdb) set opella-target arcem

This then worked correctly with our gdb server when asked for a 'g' 
packet or individual registers
*Q1. Is there a way to get the same behavior, because it appears that 
the option 'set opella-target arcem' no longer exists*

> There are some requirements to XML file - first 68 registers has 
> predefined meaning and fixed features. After those XML target 
> description may provide any XML features and registers. List of 
> supported features is described in GDB documentation in section G.4.2 
> "Target Descriptions / Standard Target Features / ARC Features". You 
> can also look into |gdb/features/arc| directory, which has examples 
> descriptions of required features and registers. It also contains 
> "compatible" register definitions - those are similar to GDB 7.5 fixed 
> register set.
>
I will take a look at the documentation to which you refer.
*Q2. Is the XML referenced at Compile time (when building gdb) or Run 
time (when executing gdb)*
*Q3. Does the XML need to exist in the installation tree at runtime ? 
After building/installing, I do not see the XML**
**in the installation tree, only in the source tree*


> You shouldn't be using |set arch| command in normal case - 
> architecture is read from application ELF file. Also XML target 
> description may contain |<architecture>| tag that will override 
> everything.
>

In out particular case, we sometimes do not provide the executable file 
to the gdb client, so we require that the gdb client is able to understand
the format of the gdbserver running in the target.

I am sorry if my questions seem basic, but we are struggling to match 
the gdb server to the gdb client - hence our difficulty.

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

> Q1.  Is there a way to get the same behavior, because it appears that the option 'set opella-target arcem' no longer exists*

You can get similar behaviour with `set tdesc filename opella-arcem-tdesc.xml`. Where this file is  https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/blob/arc-dev/extras/opella-xd/opella-arcem-tdesc.xml. Note that in this case your gdbserver should supply registers in order that is equal to described in this file. Also in comparison to `set arc opella-target arcem` order of registers is different for STATUS32, LP_START, LP_END, PC. Also new files should come with new Opella-XD software release.

> I will take a look at the documentation to which you refer.

Another source of information (which unlike others is always correct and never incomplete) is of course source code https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-7.9-dev/gdb/arc-tdep.c#L2502 . It's not huge and even have some comments, so perhaps can be easier to understand than documentation.

> *Q2. Is the XML referenced at Compile time (when building gdb) or Run
time (when executing gdb)*

File is referenced at Run time. Which is kind of the point of all of this stuff - to allow extensible GDB targets without recompilation of GDB itself.

> *Q3. Does the XML need to exist in the installation tree at runtime ?
After building/installing, I do not see the XML in the installation tree, only in the source tree*

Not really, XML file may exist anywhere if file path is provided to GDB. In fact, ideally your GDBserver should supply content of this XML file automatically to GDB client as a response to `qXfer:features:read` [packet](https://sourceware.org/gdb/onlinedocs/gdb/General-Query-Packets.html#General-Query-Packets) - then user will not need to choose XML file manually. For example, for ARC this is implemented in our OpenOCD port.

> In out particular case, we sometimes do not provide the executable file
to the gdb client, so we require that the gdb client is able to understand
the format of the gdbserver running in the target.

Then indeed you should use `set arch` or its alternatives. However if you use XML target descriptions it makes sense to put architecture there - it will have higher precedence than whatever is set with `set arch` and will remove one more step on the client side.

Anton

**Comment by leemoore1966** [comment]
Hi Anton,

This is starting to make sense, can I ask for clarification on the 
following :-

1. Mandatory xml
it seems as though there is some mandatory xml that is required by the 
client gdb, in fact it appears that the target MUST supply
something called "aux-minimal.xml".
is there a way to determine what is mandatory and what is optional ?

2. in the mail below, you say
> Note that in this case your gdbserver should supply registers in order 
> that is equal to described in this file. Also in comparison to |set 
> arc opella-target arcem| *order of registers is different for 
> STATUS32, LP_START, LP_END, PC*. Also new files should come with new 
> Opella-XD software release.
I am not quite sure what is meant here, the order is different, but 
different to what ?
I could not find anything which indicated the register indexes other 
than the indexes specified in aux-minimal.xml
Are you referring to status32(aux-minimal.xml) compared to status32_l1 & 
status32_l2 (aux-compatible.xml)?

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

`aux-minimal.xml` is sourced by `compatible-v2.xml` but is not required otherwise file can be found in https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-7.9-dev/gdb/features/arc/aux-minimal.xml.

I refer to difference between new order of registers and what was used in old Opella files and in the `set arc opella-target`, it was here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/blob/12475437ea232d11cdec888b0e2d26eed94cd9b4/extras/opella-xd/arc-opella-em.xml.

**Comment by leemoore1966** [comment]
Hi Anton
>
> |aux-minimal.xml| is sourced by |compatible-v2.xml| but is not 
> required otherwise file can be found in 
> https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-7.9-dev/gdb/features/arc/aux-minimal.xml.
>
Your description matches what I was thinking, but in practice, if 
aux-minimal.xml is not loaded the gdb fails for the following reasons
There seem to be some hardcoded requirements in the gdb source for arc.

> arc-tdep.c
>
>   269 static const char * const
>   270   aux_base_v2_feature_name = "*org.gnu.gdb.arc.aux-minimal*";
>
>
> 2662   /* Mandatory AUX registeres are intentionally few and are common between
> 2663    * ARCompact and ARC v2, so same code can be used for both. */
> 2664   feature = tdesc_find_feature (tdesc, aux_base_v2_feature_name);
> 2665   if (!feature)
> 2666     {
> 2667       fprintf_unfiltered (gdb_stdlog, "Error: Cannot find required feature "
> 2668           "`%s' in supplied target description.\n", aux_base_v2_feature_name);
> 2669       tdesc_data_cleanup (tdesc_data);
> 2670       return NULL;
> 2671     }
>

So as an experiment I tried to create my own XML representation on based 
upon the opella-arcem-tdesc.xml 
<https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/blob/arc-dev/extras/opella-xd/opella-arcem-tdesc.xml>.
I removed the reference to the inclusion of aux-minimal.xml 
<https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-7.9-dev/gdb/features/arc/aux-minimal.xml>. 
but then the loading failed due to the test in the
C code shown above.

So what I was asking in my previous mail, is there any way I can 
determine what is mandatory, and what is
optional, because it does appear that the loading of aux-minimal.xml is 
mandatory, otherwise there is a
fail during the call of arc_gdbarch_init()

The XML representation definitely seems a better way to go, and I need 
to have an understanding of what
is mandatory/optional in the XML supplied to gdb

Many Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee.

File is not mandatory and is not referenced in the source code. It is XML feature that is required and aux-minimal.xml file is a reference implementation of that feature. This file can be either source or its XML feature can be copy-pasted into your final XML file, whatever is more convenient.

As already mentioned requirements are described in G.4.2 Section of GDB User Manual

![gdb](https://cloud.githubusercontent.com/assets/602123/8207578/1d3caa40-150b-11e5-88ca-0adb052db7a0.png)
